### ISSUE TITLE
No serial output, no network pass code

### ISSUE THREAD

**Issue by RudyFiero** [matthewg42/EspApConfigurator#2]
I saw the AP but I couldn't do anything without a pass code. I assume this was put out the serial port. But i have no serial output from your program. I did a      Serial.print("Hello");  at the top of Setup() and that was sent. Nothing after that. I tried looking for DBLN but I didn't have any luck.

I was going to open an issue on the missing includes but I ended up finding your Mutila repository.  Maybe add a link to it.

**Comment by matthewg42** [comment]
Hey Rudy, cool to know someone's giving it a try - feedback is very useful, thanks!
The default AP passphrase is stored in src/EspApConfiguratorConfig.h and is "configure". However, I recommend that you explicitly set this in your code to something else by calling EspApConfigurator.setApDetails(ssid, pass). 
See [the docuementation for this function here](https://matthewg42.github.io/EspApConfigurator/classEspApConfigurator__.html#a7da990435c3cec6a166b01d1872b65d4) for details.
I'll put some notes about Mutila in the README.md file.
Thanks!

**Comment by matthewg42** [comment]
README.md updated.  Ima close this issue.  Thanks for the feedback!
